# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateField(auto_now=True, verbose_name='Deadline'),
        ),
    ]
