# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20160709_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 9, 22, 16, 35, 14567, tzinfo=utc), verbose_name='Deadline'),
        ),
    ]
