# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20160709_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 10, 35, 16, 898277, tzinfo=utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Text'),
        ),
    ]
